### ISSUE TITLE
Does not work under torch 1.0.1 version

### ISSUE THREAD

**Issue by hyeseonko** [mveres01/pytorch-drl4vrp#7]
Hi,

When I try to run trainer.py with the task = 'vrp', the error message as below comes up. is it a version issue? (device= 'cpu')

Traceback (most recent call last):
  File "D:/LG_RL/pytorch-drl4vrp-master/trainer.py", line 390, in <module>
    train_vrp(args)
  File "D:/LG_RL/pytorch-drl4vrp-master/trainer.py", line 348, in train_vrp
    train(actor, critic, **kwargs)
  File "D:/LG_RL/pytorch-drl4vrp-master/trainer.py", line 164, in train
    tour_indices, tour_logp = actor(static, dynamic, x0)
  File "C:\Users\hsko0\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\LG_RL\pytorch-drl4vrp-master\model.py", line 224, in forward
    dynamic = self.update_fn(dynamic, ptr.data)
  File "D:\LG_RL\pytorch-drl4vrp-master\tasks\vrp.py", line 135, in update_dynamic
    return torch.Tensor(tensor.data, device=dynamic.device)
**TypeError: new(): data must be a sequence (got Tensor)**

Process finished with exit code 1

Best,
Hyeseon

**Comment by mengting456** [comment]
Hello, I also have this problem . Can you solve it?How is this problem solved?
